[package]
name = "cli-image-processing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
image = "0.24.5"
imageproc = "0.23.0"
clap = {version = "4.1.8", features = ["derive"]}
crossbeam = "0.8.2"

